const STATUSES = {
  LEAD: {
    NEW: 'NEW',
    CONTACTED: 'CONTACTED',
    FOLLOW_UP: 'FOLLOW_UP',
    QUALIFIED: 'QUALIFIED',
    LOST: 'LOST'
  },
  CUSTOMER: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BLOCKED: 'BLOCKED'
  },
  QUOTATION: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SENT: 'SENT',
    NEGOTIATION: 'NEGOTIATION',
    REVISION_REQUIRED: 'REVISION_REQUIRED',
    ACCEPTED: 'ACCEPTED',
    EXPIRED: 'EXPIRED',
    CANCELLED: 'CANCELLED'
  },
  QUOTATION_REVISION: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    SENT: 'SENT',
    ACCEPTED: 'ACCEPTED',
    SUPERSEDED: 'SUPERSEDED'
  },
  PROFORMA_INVOICE: {
    DRAFT: 'DRAFT',
    ISSUED: 'ISSUED',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    PAID: 'PAID',
    CANCELLED: 'CANCELLED'
  },
  CUSTOMER_PO: {
    RECEIVED: 'RECEIVED',
    IN_VERIFICATION: 'IN_VERIFICATION',
    VERIFIED: 'VERIFIED',
    HOLD: 'HOLD',
    CANCELLED: 'CANCELLED'
  },
  PO_VERIFICATION: {
    PENDING: 'PENDING',
    MATCH: 'MATCH',
    MISMATCH: 'MISMATCH',
    HOLD: 'HOLD',
    OVERRIDDEN: 'OVERRIDDEN'
  },
  SALES_ORDER: {
    DRAFT: 'DRAFT',
    CONFIRMED: 'CONFIRMED',
    IN_PRODUCTION: 'IN_PRODUCTION',
    PRODUCTION_COMPLETED: 'PRODUCTION_COMPLETED',
    READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
    DISPATCHED: 'DISPATCHED',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  PAYMENT: {
    PENDING: 'PENDING',
    RECEIVED: 'RECEIVED',
    VERIFIED: 'VERIFIED',
    PARTIAL: 'PARTIAL',
    FAILED: 'FAILED',
    REVERSED: 'REVERSED',
    REFUNDED: 'REFUNDED'
  },
  PRODUCTION_ORDER: {
    DRAFT: 'DRAFT',
    RELEASED: 'RELEASED',
    MATERIAL_REQUESTED: 'MATERIAL_REQUESTED',
    MATERIAL_READY: 'MATERIAL_READY',
    IN_PROGRESS: 'IN_PROGRESS',
    ON_HOLD: 'ON_HOLD',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  BOM: {
    DRAFT: 'DRAFT',
    ACTIVE: 'ACTIVE',
    OBSOLETE: 'OBSOLETE'
  },
  MATERIAL_REQUEST: {
    DRAFT: 'DRAFT',
    SUBMITTED: 'SUBMITTED',
    APPROVED: 'APPROVED',
    PARTIALLY_ISSUED: 'PARTIALLY_ISSUED',
    ISSUED: 'ISSUED',
    CANCELLED: 'CANCELLED'
  },
  INVENTORY_MOVEMENT: {
    OPENING: 'OPENING',
    GRN_RECEIPT: 'GRN_RECEIPT',
    RESERVATION: 'RESERVATION',
    ISSUE: 'ISSUE',
    CONSUMPTION: 'CONSUMPTION',
    RETURN: 'RETURN',
    TRANSFER_OUT: 'TRANSFER_OUT',
    TRANSFER_IN: 'TRANSFER_IN',
    ADJUSTMENT: 'ADJUSTMENT',
    SERVICE_ISSUE: 'SERVICE_ISSUE',
    SERVICE_RETURN: 'SERVICE_RETURN'
  },
  PROCUREMENT_RFQ: {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    QUOTES_RECEIVED: 'QUOTES_RECEIVED',
    EVALUATED: 'EVALUATED',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED'
  },
  VENDOR_QUOTATION: {
    SUBMITTED: 'SUBMITTED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED'
  },
  VENDOR_PO: {
    DRAFT: 'DRAFT',
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    APPROVED: 'APPROVED',
    ISSUED: 'ISSUED',
    PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
  },
  GRN: {
    PENDING_INSPECTION: 'PENDING_INSPECTION',
    ACCEPTED: 'ACCEPTED',
    PARTIALLY_ACCEPTED: 'PARTIALLY_ACCEPTED',
    REJECTED: 'REJECTED'
  },
  PRODUCTION_OPERATION: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    PAUSED: 'PAUSED',
    COMPLETED: 'COMPLETED'
  },
  QA_TEST: {
    PENDING: 'PENDING',
    IN_TESTING: 'IN_TESTING',
    PASSED: 'PASSED',
    FAILED: 'FAILED',
    RECTIFIED: 'RECTIFIED',
    RETESTED: 'RETESTED',
    REWORK: 'REWORK',
    SCRAPPED: 'SCRAPPED'
  },
  SERIAL_NUMBER: {
    CREATED: 'CREATED',
    IN_PRODUCTION: 'IN_PRODUCTION',
    QA_PASSED: 'QA_PASSED',
    PACKED: 'PACKED',
    DISPATCHED: 'DISPATCHED',
    DELIVERED: 'DELIVERED',
    WARRANTY_ACTIVE: 'WARRANTY_ACTIVE',
    SERVICE_ACTIVE: 'SERVICE_ACTIVE',
    REPLACED: 'REPLACED',
    DECOMMISSIONED: 'DECOMMISSIONED'
  },
  PACKING_LIST: {
    PENDING: 'PENDING',
    PACKED: 'PACKED',
    INSPECTED: 'INSPECTED'
  },
  FINAL_INVOICE: {
    DRAFT: 'DRAFT',
    POSTED: 'POSTED',
    PARTIALLY_PAID: 'PARTIALLY_PAID',
    PAID: 'PAID',
    CANCELLED: 'CANCELLED'
  },
  DISPATCH: {
    DRAFT: 'DRAFT',
    READY: 'READY',
    DISPATCHED: 'DISPATCHED'
  },
  DELIVERY: {
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED',
    RESCHEDULED: 'RESCHEDULED',
    RETURNED: 'RETURNED'
  },
  INSTALLATION: {
    SCHEDULED: 'SCHEDULED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED'
  },
  COMMISSIONING: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    PASSED: 'PASSED',
    FAILED: 'FAILED'
  },
  WARRANTY: {
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
    VOIDED: 'VOIDED'
  },
  SERVICE_TICKET: {
    OPEN: 'OPEN',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    DIAGNOSIS: 'DIAGNOSIS',
    AWAITING_SPARE: 'AWAITING_SPARE',
    AWAITING_APPROVAL: 'AWAITING_APPROVAL',
    REPAIR: 'REPAIR',
    TESTING: 'TESTING',
    RESOLVED: 'RESOLVED',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED'
  },
  SERVICE_QUOTATION: {
    DRAFT: 'DRAFT',
    SENT: 'SENT',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
  },
  RMA: {
    REQUESTED: 'REQUESTED',
    APPROVED: 'APPROVED',
    RECEIVED_AT_PLANT: 'RECEIVED_AT_PLANT',
    INSPECTED: 'INSPECTED',
    REPAIR_IN_PROGRESS: 'REPAIR_IN_PROGRESS',
    REPLACED: 'REPLACED',
    CREDIT_NOTE_ISSUED: 'CREDIT_NOTE_ISSUED',
    REFUNDED: 'REFUNDED',
    CLOSED: 'CLOSED'
  }
};

module.exports = STATUSES;
